/**
 * Bakes the real conformance run into `site/data.js` so the microsite shows live
 * results with zero runtime/server. Regenerate with `npm run gen:site`.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { runConformance } from "../src/runner.js";
import { referenceAdapter } from "../src/reference-adapter.js";

const report = await runConformance(referenceAdapter);
const here = dirname(fileURLToPath(import.meta.url));
const payload = {
  generatedFor: "@goodmeta/agent-verifier (reference adapter)",
  ap2Commit: "e1ea56db72a6385bce3e5c1112b3a56ce60acb43",
  ...report,
};
writeFileSync(
  join(here, "data.js"),
  `// Generated by site/gen-data.ts — do not edit by hand. Run: npm run gen:site\nwindow.__AP2_CONFORMANCE__ = ${JSON.stringify(payload, null, 2)};\n`,
);
console.log(`wrote site/data.js — ${report.results.length} results, conformant=${report.conformant}`);
